name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Download modules
      env:
        GOPROXY: "https://proxy.golang.org,direct"
      run: go mod download

    - name: Build
      run: make build

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 30

    - name: Log in Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Download modules
      env:
        GOPROXY: "https://proxy.golang.org,direct"
      run: go mod download

    - name: Bump version
      id: bump_version
      run: |
        go run cmd/main.go
        echo "##[set-output name=version;]$(git describe --abbrev=0)"

    - name: Publish version
      run: git push --follow-tags origin release

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.version }}
        release_name: Version ${{ steps.bump_version.outputs.version }}
        draft: false
        prerelease: false
